language: php
php:
  - 5.6
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin

install:
  - composer self-update

script:
  - scripts/setup-dev-env.sh
  - grumphp run

notifications:
  email: false